# Generated by Django 5.0.1 on 2024-01-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_historicaltask'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='history',
            table='task_manager_historicaltask',
        ),
    ]
